export const LEGAL_CONTACT_EMAIL = "support@elmtrackr.site";

// Canonical legal pages now live on the marketing site.
export const PRIVACY_POLICY_URL = "https://elmtrackr.site/privacy";
export const TERMS_URL = "https://elmtrackr.site/terms";

export const PRIVACY_POLICY_LAST_UPDATED = "September 9, 2026";

export const privacyPolicySections = [
  {
    title: "Overview",
    body:
      "ElmTrackr (“we”, “the app”) helps you track work shifts, estimate pay, and manage travel refund claims. This policy explains what we collect, why, and your choices.",
  },
  {
    title: "Data we collect",
    body:
      "Account: email address and optional display name when you sign up. Work data: shift times, breaks, notes, overtime settings, compensation rules, and pay estimates you configure. Refunds: travel claim details and receipt photos you upload. Device: the app stores data locally on your phone and syncs to our cloud database when you are signed in.",
  },
  {
    title: "Crash reports and diagnostics",
    body:
      "When crash reporting is on — it is on by default and you can turn it off in Settings → Help & About → Share crash reports — a failure sends a technical report to Sentry, our crash-reporting processor. It contains the error and its stack trace, your device model and Android version, the app version, a short trail of the screens and actions leading up to the failure, and a random identifier for the installation, which lets us tell one device's crashes from another's. It does not contain your name, your email address, your shifts, your pay or your receipts, and identifying values are stripped from error text before the report is sent. The Wear OS app does the same, following the setting you choose on the phone.",
  },
  {
    title: "How we use data",
    body:
      "We use your data only to provide app features: clock in/out, reports, pay estimates, refund tracking, and sync across devices. Pay figures are estimates for your personal reference — not official payroll.",
  },
  {
    title: "Where data is stored",
    body:
      "Cloud data is hosted on Supabase (PostgreSQL and object storage). Local data remains in an on-device database until you delete it or uninstall the app.",
  },
  {
    title: "Sharing",
    body:
      "We do not sell your personal data, and we use no advertising SDKs and no advertising or marketing trackers. Data reaches two processors, both acting on our instructions: Supabase, which hosts the database and receipt storage, and Sentry, which receives crash reports and app-health diagnostics when crash reporting is left on. You can turn crash reporting off at any time in Settings → Help & About → Share crash reports.",
  },
  {
    title: "Retention & deletion",
    body:
      "You can delete your account at any time from Settings → Account → Delete account. This permanently removes your cloud profile, shifts, settings, refund claims, and uploaded receipts. Local app data on your device is cleared when you delete your account from the app.",
  },
  {
    title: "Your rights",
    body:
      "Depending on your region, you may have rights to access, correct, or delete your data. Use in-app account deletion or contact us at the email below.",
  },
  {
    title: "Contact",
    body: `Questions about privacy: ${LEGAL_CONTACT_EMAIL}`,
  },
] as const;

export const termsSections = [
  {
    title: "Acceptance",
    body:
      "By using ElmTrackr you agree to these Terms. If you do not agree, do not use the app.",
  },
  {
    title: "Service description",
    body:
      "ElmTrackr is a personal shift and hours tracking tool. Pay and overtime figures are estimates only and do not constitute tax, legal, or payroll advice.",
  },
  {
    title: "Your account",
    body:
      "You are responsible for keeping your login credentials secure. You must provide accurate information. You may delete your account at any time from Settings.",
  },
  {
    title: "Acceptable use",
    body:
      "Do not misuse the service, attempt unauthorized access, or upload unlawful content. Receipt photos should only be those you have the right to store.",
  },
  {
    title: "Availability",
    body:
      "We strive for reliable service but do not guarantee uninterrupted access. The Android app supports offline use; cloud sync requires an internet connection.",
  },
  {
    title: "Limitation of liability",
    body:
      "To the fullest extent permitted by law, ElmTrackr is provided “as is”. We are not liable for decisions you make based on pay estimates or reports generated by the app.",
  },
  {
    title: "Changes",
    body:
      "We may update these Terms. Continued use after changes constitutes acceptance. Material changes will be reflected in the “Last updated” date on this page.",
  },
  {
    title: "Contact",
    body: `Questions: ${LEGAL_CONTACT_EMAIL}`,
  },
] as const;
