import type { RefundClaim, Shift } from "@/types";

export interface ExportRow {
  shift: Shift;
  claim: RefundClaim;
}

function monthName(month: number): string {
  return new Date(2000, month - 1, 1).toLocaleString("en-US", { month: "long" });
}

function fmt(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export async function exportRefundPdf(
  rows: ExportRow[],
  year: number,
  month: number,
  employeeName?: string | null
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Travel Reimbursement Report", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`${monthName(month)} ${year}`, margin, y);
  if (employeeName) {
    doc.text(employeeName, pageW - margin, y, { align: "right" });
  }
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Summary
  const total = rows.reduce((sum, r) => sum + r.claim.amount, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total claims: ${rows.length}`, margin, y);
  doc.text(`Total amount: ₪${total.toFixed(2)}`, pageW - margin, y, { align: "right" });
  y += 10;

  // Table header
  const colX = { date: margin, shift: margin + 30, provider: margin + 85, amount: pageW - margin };
  doc.setFillColor(245, 245, 250);
  doc.rect(margin, y - 4, pageW - margin * 2, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Ride date", colX.date, y);
  doc.text("Shift end", colX.shift, y);
  doc.text("Provider", colX.provider, y);
  doc.text("Amount", colX.amount, y, { align: "right" });
  y += 4;

  doc.line(margin, y, pageW - margin, y);
  y += 4;

  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  for (const { shift, claim } of rows) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }

    doc.text(fmt(claim.ride_at), colX.date, y, { maxWidth: 28 });
    doc.text(shift.end_time ? fmt(shift.end_time) : "—", colX.shift, y, { maxWidth: 53 });
    doc.text(claim.provider, colX.provider, y, { maxWidth: 30 });
    doc.text(`₪${claim.amount.toFixed(2)}`, colX.amount, y, { align: "right" });
    y += 5;

    if (claim.notes) {
      doc.setTextColor(120, 120, 130);
      doc.setFontSize(8);
      doc.text(`Note: ${claim.notes}`, colX.date + 2, y, { maxWidth: pageW - margin * 2 - 4 });
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(9);
      y += 4;
    }

    // Light row divider
    doc.setDrawColor(230, 230, 235);
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  }

  // Footer total
  y += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Total: ₪${total.toFixed(2)}`, pageW - margin, y, { align: "right" });

  // Generated timestamp
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by ElmTrackr on ${new Date().toLocaleDateString()}`, margin, y);

  doc.save(`refund-${year}-${String(month).padStart(2, "0")}.pdf`);
}
