import type { RefundClaim, Shift } from "@/types";

export interface ExportRow {
  shift: Shift;
  claim: RefundClaim;
  receiptDataUrl?: string; // base64 data URL fetched before calling exportRefundPdf
}

function monthName(month: number): string {
  return new Date(2000, month - 1, 1).toLocaleString("en-US", { month: "long" });
}

function fmt(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export async function exportRefundPdf(
  rows: ExportRow[],
  year: number,
  month: number,
  employeeName?: string | null
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  let y = margin;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Travel Reimbursement Report", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`${monthName(month)} ${year}`, margin, y);
  if (employeeName) {
    doc.text(employeeName, pageW - margin, y, { align: "right" });
  }
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Summary
  const total = rows.reduce((sum, r) => sum + r.claim.amount, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total claims: ${rows.length}`, margin, y);
  doc.text(`Total amount: ILS ${total.toFixed(2)}`, pageW - margin, y, { align: "right" });
  y += 10;

  // Table header
  const colX = { direction: margin, date: margin + 22, shift: margin + 52, provider: margin + 92, amount: pageW - margin };
  doc.setFillColor(245, 245, 250);
  doc.rect(margin, y - 4, pageW - margin * 2, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Direction", colX.direction, y);
  doc.text("Ride date", colX.date, y);
  doc.text("Shift time", colX.shift, y);
  doc.text("Provider", colX.provider, y);
  doc.text("Amount", colX.amount, y, { align: "right" });
  y += 4;

  doc.line(margin, y, pageW - margin, y);
  y += 4;

  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  for (const { shift, claim } of rows) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }

    const dirLabel = claim.direction === "to_work" ? "→ To work" : "← From work";
    const shiftTime = claim.direction === "to_work"
      ? fmt(shift.start_time)
      : (shift.end_time ? fmt(shift.end_time) : "—");

    doc.text(dirLabel, colX.direction, y, { maxWidth: 20 });
    doc.text(fmt(claim.ride_at), colX.date, y, { maxWidth: 28 });
    doc.text(shiftTime, colX.shift, y, { maxWidth: 38 });
    doc.text(claim.provider, colX.provider, y, { maxWidth: 28 });
    doc.text(`ILS ${claim.amount.toFixed(2)}`, colX.amount, y, { align: "right" });
    y += 5;

    if (claim.notes) {
      doc.setTextColor(120, 120, 130);
      doc.setFontSize(8);
      doc.text(`Note: ${claim.notes}`, colX.date + 2, y, { maxWidth: pageW - margin * 2 - 4 });
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(9);
      y += 4;
    }

    doc.setDrawColor(230, 230, 235);
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  }

  // Footer total
  y += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Total: ILS ${total.toFixed(2)}`, pageW - margin, y, { align: "right" });

  // Generated timestamp
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by ElmTrackr on ${new Date().toLocaleDateString()}`, margin, y);

  // ── Receipt image pages ────────────────────────────────────────────────────
  const rowsWithImages = rows.filter((r) => r.receiptDataUrl);
  if (rowsWithImages.length > 0) {
    doc.addPage();
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Receipts", margin, margin);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, margin + 4, pageW - margin, margin + 4);

    let ry = margin + 12;

    for (let i = 0; i < rowsWithImages.length; i++) {
      const { claim, receiptDataUrl } = rowsWithImages[i];

      // Caption
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 80);
      doc.text(
        `${i + 1}. ${claim.provider} · ILS ${claim.amount.toFixed(2)} · ${fmt(claim.ride_at)}`,
        margin,
        ry
      );
      ry += 4;

      // Image — fit within available space, preserve aspect ratio
      const img = new window.Image();
      await new Promise<void>((resolve) => {
        img.onload = () => resolve();
        img.onerror = () => resolve(); // skip on error
        img.src = receiptDataUrl!;
      });

      if (img.naturalWidth > 0 && img.naturalHeight > 0) {
        const maxW = pageW - margin * 2;
        const maxH = pageH - ry - margin - 10;
        const aspect = img.naturalWidth / img.naturalHeight;
        let imgW = maxW;
        let imgH = imgW / aspect;
        if (imgH > maxH) {
          imgH = maxH;
          imgW = imgH * aspect;
        }

        // If image won't fit on this page, add a new one
        if (ry + imgH > pageH - margin) {
          doc.addPage();
          ry = margin;
          // Reprint caption on new page
          doc.setFont("helvetica", "bold");
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 80);
          doc.text(
            `${i + 1}. ${claim.provider} · ILS ${claim.amount.toFixed(2)} · ${fmt(claim.ride_at)}`,
            margin,
            ry
          );
          ry += 4;
          imgH = Math.min(imgH, pageH - ry - margin - 4);
          imgW = imgH * aspect;
        }

        doc.addImage(receiptDataUrl!, margin, ry, imgW, imgH);
        ry += imgH + 10;
      }

      // Start each receipt on a fresh page (except the last one)
      if (i < rowsWithImages.length - 1) {
        doc.addPage();
        ry = margin;
      }
    }
  }

  const namePart = employeeName
    ? employeeName.trim().toLowerCase().replace(/\s+/g, "_")
    : "user";
  doc.save(`${namePart}_rides_${monthName(month).toLowerCase()}_${year}.pdf`);
}
