package com.elmtrackr.app.ui.reports

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.elmtrackr.app.domain.MonthlyReportBuilder
import com.elmtrackr.app.domain.model.RefundClaim
import com.elmtrackr.app.domain.MoneyFormatter
import com.elmtrackr.app.domain.model.CurrencyCode
import com.elmtrackr.app.domain.model.RefundDirection
import com.elmtrackr.app.domain.model.Shift
import com.elmtrackr.app.domain.ShiftDurationCalculator
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.net.URL
import java.time.Month
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.util.Locale

data class RefundPdfRow(
    val shift: Shift,
    val claim: RefundClaim,
    val receipt: Bitmap? = null,
)

object ReportExporter {
    fun shareCsv(context: Context, content: String, filename: String) {
        val file = exportFile(context, filename).apply { writeText(content) }
        shareFile(context, file, "text/csv", "Export CSV")
    }

    fun shareShiftPdf(
        context: Context,
        state: ReportsUiState.Ready,
    ) {
        val filename = "elmtrackr-shifts-${state.year}-${state.month.toString().padStart(2, '0')}.pdf"
        val file = exportFile(context, filename)
        val document = PdfDocument()
        val pageWidth = 595
        val pageHeight = 842
        val margin = 40f
        val title = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 21f; isFakeBoldText = true; color = AuroraPdfInk }
        val subtitle = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 10f; color = AuroraPdfMuted }
        val heading = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 10f; isFakeBoldText = true; color = AuroraPdfInk }
        val body = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 8.5f; color = AuroraPdfInk }
        val muted = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 8f; color = AuroraPdfMuted }
        val line = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = AuroraPdfHair; strokeWidth = 1f }
        val fill = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = AuroraPdfSubtle }
        val accent = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = AuroraPdfIndigo; strokeWidth = 7f }
        val plum = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = AuroraPdfPlum; strokeWidth = 7f }
        val peach = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = AuroraPdfPeach; strokeWidth = 7f }
        val currency = state.settings?.currency ?: CurrencyCode.ILS
        val monthLabel = "${Month.of(state.month).getDisplayName(TextStyle.FULL, Locale.getDefault())} ${state.year}"
        val zone = ZoneId.systemDefault()
        val dateFormat = DateTimeFormatter.ofPattern("EEE, dd MMM").withZone(zone)
        val timeFormat = DateTimeFormatter.ofPattern("HH:mm").withZone(zone)

        var pageNumber = 1
        var page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create())
        var canvas = page.canvas
        var y = margin

        fun newPage() {
            canvas.drawText("Generated by ElmTrackr", margin, pageHeight - margin, muted)
            document.finishPage(page)
            pageNumber += 1
            page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create())
            canvas = page.canvas
            y = margin
        }

        fun ensureSpace(required: Float) {
            if (y + required > pageHeight - margin - 18f) newPage()
        }

        canvas.drawText("Monthly Shift Report", margin, y, title)
        canvas.drawText(monthLabel, pageWidth - margin, y, heading.apply { textAlign = Paint.Align.RIGHT })
        heading.textAlign = Paint.Align.LEFT
        y += 18f
        canvas.drawText("${state.report.shiftCount} completed shifts", margin, y, subtitle)
        y += 22f

        canvas.drawRoundRect(margin, y, pageWidth - margin, y + 84f, 18f, 18f, fill)
        y += 20f
        canvas.drawText("Hours Distribution", margin + 16f, y, heading)
        canvas.drawText(ShiftDurationCalculator.formatMinutes(state.report.totalMinutes), pageWidth - margin - 16f, y, heading.apply { textAlign = Paint.Align.RIGHT })
        heading.textAlign = Paint.Align.LEFT
        y += 18f
        drawMetric(canvas, "Regular", ShiftDurationCalculator.formatMinutes(state.report.regularMinutes), margin + 16f, y, body, muted)
        drawMetric(canvas, "Overtime", ShiftDurationCalculator.formatMinutes(state.report.overtimeMinutes), margin + 155f, y, body, muted)
        drawMetric(canvas, "Weekend", ShiftDurationCalculator.formatMinutes(state.report.weekendMinutes), margin + 294f, y, body, muted)
        state.paySummary?.let { pay ->
            drawMetric(canvas, "Gross pay", MoneyFormatter.format(pay.totalGross, currency), pageWidth - margin - 116f, y, body, muted)
        }
        y += 28f
        drawDistributionBar(canvas, margin + 16f, y, pageWidth - margin * 2 - 32f, state.report.totalMinutes, state.report.regularMinutes, state.report.overtimeMinutes, state.report.weekendMinutes, accent, peach, plum)
        y += 38f

        state.paySummary?.takeIf { it.totalGross > 0.0 }?.let { pay ->
            ensureSpace(70f)
            canvas.drawText("Gross Pay - Before Tax", margin, y, heading)
            y += 17f
            drawMetric(canvas, "Regular", MoneyFormatter.format(pay.regularGross, currency), margin, y, body, muted)
            drawMetric(canvas, "Overtime", MoneyFormatter.format(pay.overtimeGross, currency), margin + 150f, y, body, muted)
            drawMetric(canvas, "Holiday", MoneyFormatter.format(pay.specialGross, currency), margin + 300f, y, body, muted)
            drawMetric(canvas, "Total", MoneyFormatter.format(pay.totalGross, currency), pageWidth - margin - 95f, y, body, muted)
            y += 30f
        }

        if (state.weeklyTotals.isNotEmpty()) {
            ensureSpace(70f)
            canvas.drawText("Weekly Breakdown", margin, y, heading)
            y += 14f
            state.weeklyTotals.forEach { week ->
                ensureSpace(18f)
                canvas.drawLine(margin, y, pageWidth - margin, y, line)
                y += 12f
                canvas.drawText("${week.label} (days ${week.dayRange})", margin, y, body)
                canvas.drawText(
                    ShiftDurationCalculator.formatMinutes(week.totalMinutes),
                    pageWidth - margin,
                    y,
                    body.apply { textAlign = Paint.Align.RIGHT },
                )
                body.textAlign = Paint.Align.LEFT
                y += 12f
            }
            y += 10f
        }

        state.settings?.let { settings ->
            ensureSpace(42f)
            canvas.drawText("Thresholds", margin, y, heading)
            y += 14f
            canvas.drawText(
                "Daily OT after ${ShiftDurationCalculator.formatMinutes(settings.dailyOvertimeThresholdMinutes)}   Weekly OT after ${ShiftDurationCalculator.formatMinutes(settings.weeklyOvertimeThresholdMinutes)}",
                margin,
                y,
                muted,
            )
            y += 24f
        }

        ensureSpace(56f)
        canvas.drawText("Shift Breakdown", margin, y, heading)
        y += 16f
        drawShiftHeader(canvas, margin, y, heading, fill)
        y += 18f

        state.rawShifts.sortedBy { it.startTime }.forEach { shift ->
            ensureSpace(38f)
            val breakdown = state.settings?.let { MonthlyReportBuilder.buildShiftBreakdown(shift, it) }
            val pay = state.settings?.let { settings ->
                settings.hourlyRate?.takeIf { it > 0 }?.let {
                    com.elmtrackr.app.domain.PayrollCalculator.calculateShiftPay(shift, settings, state.profiles)
                }
            }
            val timeText = buildString {
                append(timeFormat.format(shift.startTime))
                append(" - ")
                append(shift.endTime?.let(timeFormat::format) ?: "Active")
                if (shift.breakMinutes > 0) append("  ${shift.breakMinutes}m break")
            }
            val tags = buildList {
                if (shift.isSpecialDay) add("Holiday")
                if ((breakdown?.weekendMinutes ?: 0) > 0 && !shift.isSpecialDay) add("Weekend")
                if (com.elmtrackr.app.domain.OvernightShiftDetector.isOvernight(shift)) add("Overnight")
            }.joinToString(" / ")
            canvas.drawText(dateFormat.format(shift.startTime), margin, y, body)
            canvas.drawText(timeText, margin + 94f, y, body)
            canvas.drawText(breakdown?.totalMinutes?.let(ShiftDurationCalculator::formatMinutes) ?: "-", margin + 230f, y, body)
            canvas.drawText(tags.ifBlank { "-" }, margin + 300f, y, muted)
            canvas.drawText(
                pay?.let { MoneyFormatter.format(it.totalGross, currency) } ?: "-",
                pageWidth - margin,
                y,
                body.apply { textAlign = Paint.Align.RIGHT },
            )
            body.textAlign = Paint.Align.LEFT
            y += 9f
            shift.notes?.takeIf { it.isNotBlank() }?.let {
                canvas.drawText("Note: ${it.take(92)}", margin + 94f, y, muted)
                y += 9f
            }
            canvas.drawLine(margin, y, pageWidth - margin, y, line)
            y += 13f
        }

        canvas.drawText("Generated by ElmTrackr", margin, pageHeight - margin, muted)
        document.finishPage(page)
        file.outputStream().use(document::writeTo)
        document.close()
        shareFile(context, file, "application/pdf", "Export shift PDF")
    }

    suspend fun loadReceipt(url: String): Bitmap? = withContext(Dispatchers.IO) {
        runCatching { URL(url).openStream().use(BitmapFactory::decodeStream) }.getOrNull()
    }

    fun shareRefundPdf(
        context: Context,
        rows: List<RefundPdfRow>,
        year: Int,
        month: Int,
        currency: CurrencyCode,
    ) {
        shareRefundPdf(
            context = context,
            rows = rows,
            filenameSuffix = "$year-${month.toString().padStart(2, '0')}",
            periodLabel = "$year-${month.toString().padStart(2, '0')}",
            currency = currency,
        )
    }

    fun shareRefundPdf(
        context: Context,
        rows: List<RefundPdfRow>,
        filenameSuffix: String,
        periodLabel: String,
        currency: CurrencyCode,
    ) {
        val filename = "elmtrackr-rides-$filenameSuffix.pdf"
        val file = exportFile(context, filename)
        val document = PdfDocument()
        val pageWidth = 595
        val pageHeight = 842
        val margin = 40f
        val title = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 20f; isFakeBoldText = true }
        val heading = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 11f; isFakeBoldText = true }
        val body = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 9f }
        val muted = Paint(Paint.ANTI_ALIAS_FLAG).apply { textSize = 8f; color = 0xff777785.toInt() }
        val line = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = 0xffddddE5.toInt(); strokeWidth = 1f }
        val dateFormat = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm").withZone(ZoneOffset.UTC)

        var pageNumber = 1
        var page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create())
        var canvas = page.canvas
        var y = margin
        canvas.drawText("Travel Reimbursement Report", margin, y, title)
        y += 24f
        canvas.drawText(periodLabel, margin, y, body)
        val total = rows.sumOf { it.claim.amount }
        canvas.drawText("${rows.size} claims", margin, y + 20f, heading)
        canvas.drawText("Total: ${MoneyFormatter.format(total, currency)}", pageWidth - margin - 130f, y + 20f, heading)
        y += 50f
        canvas.drawText("Direction", margin, y, heading)
        canvas.drawText("Ride date", 105f, y, heading)
        canvas.drawText("Provider", 280f, y, heading)
        canvas.drawText("Amount", 490f, y, heading)
        y += 8f
        canvas.drawLine(margin, y, pageWidth - margin, y, line)
        y += 16f

        rows.forEach { row ->
            if (y > pageHeight - 70f) {
                document.finishPage(page)
                pageNumber++
                page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create())
                canvas = page.canvas
                y = margin
            }
            val direction = if (row.claim.direction == RefundDirection.TO_WORK) "To work" else "From work"
            canvas.drawText(direction, margin, y, body)
            canvas.drawText(dateFormat.format(row.claim.rideAt), 105f, y, body)
            canvas.drawText(row.claim.provider.name.lowercase().replaceFirstChar(Char::uppercase), 280f, y, body)
            canvas.drawText(MoneyFormatter.format(row.claim.amount, currency), 475f, y, body)
            y += 14f
            val detail = buildString {
                append("Shift: ").append(dateFormat.format(row.shift.startTime))
                row.claim.notes?.let { append("  Note: ").append(it.take(70)) }
                if (row.claim.receiptPath != null) append("  Receipt attached")
            }
            canvas.drawText(detail, 105f, y, muted)
            y += 12f
            canvas.drawLine(margin, y, pageWidth - margin, y, line)
            y += 16f
        }
        canvas.drawText("Generated by ElmTrackr", margin, pageHeight - margin, muted)
        document.finishPage(page)

        rows.filter { it.receipt != null }.forEachIndexed { index, row ->
            pageNumber++
            val receiptPage = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create())
            val receiptCanvas = receiptPage.canvas
            receiptCanvas.drawText(
                "Receipt ${index + 1}: ${row.claim.provider.name} - ${MoneyFormatter.format(row.claim.amount, currency)}",
                margin,
                margin,
                heading,
            )
            val bitmap = requireNotNull(row.receipt)
            val maxWidth = (pageWidth - margin * 2).toInt()
            val maxHeight = (pageHeight - margin * 2 - 24).toInt()
            val scale = minOf(maxWidth.toFloat() / bitmap.width, maxHeight.toFloat() / bitmap.height, 1f)
            val width = (bitmap.width * scale).toInt()
            val height = (bitmap.height * scale).toInt()
            val left = ((pageWidth - width) / 2f)
            val top = margin + 24f
            receiptCanvas.drawBitmap(bitmap, null, android.graphics.RectF(left, top, left + width, top + height), null)
            document.finishPage(receiptPage)
        }

        file.outputStream().use(document::writeTo)
        document.close()
        shareFile(context, file, "application/pdf", "Export reimbursement PDF")
    }

    private fun exportFile(context: Context, filename: String): File =
        File(context.cacheDir, "exports").apply { mkdirs() }.resolve(filename)

    private fun shareFile(context: Context, file: File, mimeType: String, title: String) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.files", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, title))
    }

    private fun drawMetric(
        canvas: android.graphics.Canvas,
        label: String,
        value: String,
        x: Float,
        y: Float,
        body: Paint,
        muted: Paint,
    ) {
        canvas.drawText(label.uppercase(), x, y, muted)
        canvas.drawText(value, x, y + 13f, body.apply { isFakeBoldText = true })
        body.isFakeBoldText = false
    }

    private fun drawDistributionBar(
        canvas: android.graphics.Canvas,
        x: Float,
        y: Float,
        width: Float,
        total: Int,
        regular: Int,
        overtime: Int,
        weekend: Int,
        regularPaint: Paint,
        overtimePaint: Paint,
        weekendPaint: Paint,
    ) {
        val safeTotal = total.coerceAtLeast(1).toFloat()
        var cursor = x
        listOf(regular to regularPaint, overtime to overtimePaint, weekend to weekendPaint).forEach { (minutes, paint) ->
            if (minutes <= 0) return@forEach
            val segmentWidth = width * (minutes / safeTotal)
            canvas.drawLine(cursor, y, cursor + segmentWidth, y, paint)
            cursor += segmentWidth
        }
    }

    private fun drawShiftHeader(
        canvas: android.graphics.Canvas,
        x: Float,
        y: Float,
        heading: Paint,
        fill: Paint,
    ) {
        canvas.drawRoundRect(x, y - 12f, x + 515f, y + 6f, 8f, 8f, fill)
        canvas.drawText("Date", x + 4f, y, heading)
        canvas.drawText("Time", x + 94f, y, heading)
        canvas.drawText("Total", x + 230f, y, heading)
        canvas.drawText("Tags", x + 300f, y, heading)
        canvas.drawText("Gross", x + 515f, y, heading.apply { textAlign = Paint.Align.RIGHT })
        heading.textAlign = Paint.Align.LEFT
    }

    private const val AuroraPdfInk = 0xff181530.toInt()
    private const val AuroraPdfMuted = 0xff615C8A.toInt()
    private const val AuroraPdfHair = 0x335B4DF2
    private const val AuroraPdfSubtle = 0xffF6F6FD.toInt()
    private const val AuroraPdfIndigo = 0xff5B4DF2.toInt()
    private const val AuroraPdfPlum = 0xff8B5CF6.toInt()
    private const val AuroraPdfPeach = 0xffFF9E7D.toInt()
}
