package com.elmtrackr.app.ui.settings

internal val COUNTRY_TIMEZONES = listOf(
    "Israel" to "Asia/Jerusalem", "Palestine" to "Asia/Gaza", "Jordan" to "Asia/Amman",
    "Lebanon" to "Asia/Beirut", "Syria" to "Asia/Damascus", "Iraq" to "Asia/Baghdad",
    "Iran" to "Asia/Tehran", "Saudi Arabia" to "Asia/Riyadh", "United Arab Emirates" to "Asia/Dubai",
    "Qatar" to "Asia/Qatar", "Kuwait" to "Asia/Kuwait", "Bahrain" to "Asia/Bahrain",
    "Oman" to "Asia/Muscat", "Yemen" to "Asia/Aden", "Turkey" to "Europe/Istanbul",
    "Austria" to "Europe/Vienna", "Belgium" to "Europe/Brussels", "Bulgaria" to "Europe/Sofia",
    "Switzerland" to "Europe/Zurich", "Czech Republic" to "Europe/Prague", "Germany" to "Europe/Berlin",
    "Denmark" to "Europe/Copenhagen", "Spain" to "Europe/Madrid", "Finland" to "Europe/Helsinki",
    "France" to "Europe/Paris", "United Kingdom" to "Europe/London", "Greece" to "Europe/Athens",
    "Croatia" to "Europe/Zagreb", "Hungary" to "Europe/Budapest", "Ireland" to "Europe/Dublin",
    "Italy" to "Europe/Rome", "Netherlands" to "Europe/Amsterdam", "Norway" to "Europe/Oslo",
    "Poland" to "Europe/Warsaw", "Portugal" to "Europe/Lisbon", "Romania" to "Europe/Bucharest",
    "Russia" to "Europe/Moscow", "Sweden" to "Europe/Stockholm", "Slovakia" to "Europe/Bratislava",
    "Ukraine" to "Europe/Kiev", "Argentina" to "America/Argentina/Buenos_Aires", "Brazil" to "America/Sao_Paulo",
    "Canada" to "America/Toronto", "Chile" to "America/Santiago", "Colombia" to "America/Bogota",
    "Mexico" to "America/Mexico_City", "Peru" to "America/Lima", "United States" to "America/New_York",
    "Venezuela" to "America/Caracas", "Algeria" to "Africa/Algiers", "Egypt" to "Africa/Cairo",
    "Ethiopia" to "Africa/Addis_Ababa", "Ghana" to "Africa/Accra", "Kenya" to "Africa/Nairobi",
    "Morocco" to "Africa/Casablanca", "Nigeria" to "Africa/Lagos", "Tunisia" to "Africa/Tunis",
    "South Africa" to "Africa/Johannesburg", "Australia" to "Australia/Sydney", "Bangladesh" to "Asia/Dhaka",
    "China" to "Asia/Shanghai", "Hong Kong" to "Asia/Hong_Kong", "Indonesia" to "Asia/Jakarta",
    "India" to "Asia/Kolkata", "Japan" to "Asia/Tokyo", "South Korea" to "Asia/Seoul",
    "Malaysia" to "Asia/Kuala_Lumpur", "New Zealand" to "Pacific/Auckland", "Philippines" to "Asia/Manila",
    "Pakistan" to "Asia/Karachi", "Singapore" to "Asia/Singapore", "Thailand" to "Asia/Bangkok",
    "Taiwan" to "Asia/Taipei", "Vietnam" to "Asia/Ho_Chi_Minh",
).let { options -> listOf(options.first()) + options.drop(1).sortedBy { it.first } }
